version: "3"
services:
  interview-coding-test:
    build: .
    ports:
      - 8080:8080
    restart: always
    volumes:
      - ./src:/usr/src/app/src:cached
      - ./spec:/usr/src/app/spec:cached